version: 2
updates:
 - package-ecosystem: "devcontainers"
   directory: "/"
   schedule:
     interval: weekly
 - package-ecosystem: "npm"
   directory: "./astro-site"
   schedule:
     interval: weekly
 - package-ecosystem: "npm"
   directory: "./cdk"
   schedule:
     interval: weekly
```