name: Upload artefact

on:
  push:
    types: [ labeled ]
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
upload-artifact:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: contains(github.event.pull_request.labels.*.name, 'deploy')
    defaults:
      run:
        working-directory: ./site
    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Download artefact
        uses: actions/download-artifact@v4
        with:
          name: latest-site-artifact
          path: site

      - name: zip and upload to s3
        run: |
          zip -r latest-site-artifact.zip .
          aws s3 cp latest-site-artifact.zip s3://lincolnhack-artefacts/latest-site-artifact.zip        
